### ISSUE TITLE
Remove/Downgrade node version?

### ISSUE THREAD

**Issue by LucJosin** [RodrigoTomeES/astro-rename#5]
Hi @RodrigoTomeES, thanks for this awesome Astro integration. 

I'm currently using node `18.X` and the only way to install this integration is using the `--ignore-engines`. Not really a problem but i'm wondering why the requirement of node `>=20.2`.

https://github.com/RodrigoTomeES/astro-rename/blob/44ce009567ef82067a86e4099a517a0cdeccb926/package.json#L63-L65

**Comment by RodrigoTomeES** [comment]
Hi,

@LucJosin I thought that it only affect to my project, I will downgrade it to the latest LTS. But I will update again it when node 20 LTS will be released.

Cheers!

**Comment by RodrigoTomeES** [comment]
Resolved #7
